var s = "attribute /* Look out! It's a vec3! */ vec3 pos;\n"
+"attribute float inx;\n"
+"/* Those attributes are $$$\n"
+"   I like myname@example.org.\n"
+"*/\n"
+"attribute float j;\n"
+"/*\n"
+"\n"
+"**\n"
+"\n"
+"//\n"
+"\n"
+"*\n"
+"/\n"
+"*/\n"
+"uniform float tm; // ♌\n"
+"\n"
+"void main/***/(void)\n"
+"  {\n"
+"  float/*/***/k;\n"
+"  // \frac{p}{2}\n"
+"  gl_Position/**/ = /*/*/pos/2;\n"
+"  }\n"
+"\n"
+"/* what is this comment doing down here? *///dunno, what?$\n";